title: "Sinan Rassam"

# site images
background_image: "background.jpg"
banner_image: "banner.jpg"
profile_image: "profile.jpg"

# quick details:
bio: Computer & Mobile Systems Engineering graduate from Auckland University of Technology.
interest: I am interested in working on projects and tools that will allow me to use and expand my current knowledge and experience in software and programming.
location: Auckland, New Zealand

# skills
skills:
  - Linux
  - Web Development
  - Wordpress
  - Joomla
  - HTML
  - CSS
  - JavaScript
  - PHP
  - MySQL
  - SQL
  - Android
  - Java

# roles
current_role: Software Engineer @ Les Mills International.

# education
education: Computer & Mobile Systems Engieering graduate from AUT.

# social urls
github_username:  sinanrassam
linkedin_username: sinanrassam

# Contact
formspree_key: xzbjjjay

# Analytics
google_analytics: "UA-89778108-3"
